# Generated by Django 3.2.6 on 2021-08-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premier_nom', models.CharField(max_length=100)),
                ('dernier_nom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('npa', models.CharField(max_length=100)),
                ('localite', models.CharField(max_length=100)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('paye', models.BooleanField(default=False)),
                ('montant_paye', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
