# Generated by Django 3.2.6 on 2021-08-24 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210824_2138'),
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('quantite', models.IntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commande.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='store.produit')),
            ],
        ),
    ]
