# Generated by Django 3.2.6 on 2021-08-24 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_commandeitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='dernier_nom',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='premier_nom',
            new_name='prenom',
        ),
    ]
