# Generated by Django 3.2.6 on 2021-08-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0003_auto_20210824_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandé',
            name='date_livraison',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commandé',
            name='statut',
            field=models.CharField(choices=[('commande', 'Commandé'), ('livré', 'Livré'), ('arrivé', 'Arrivé')], default='commandé', max_length=20),
        ),
    ]
