# Generated by Django 3.2.6 on 2021-08-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0005_alter_commande_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('commande', 'Commandé'), ('livre', 'Livré'), ('arrive', 'Arrivé')], default='commande', max_length=20),
        ),
    ]
