# Generated by Django 3.2.6 on 2021-08-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0007_commande_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('commandé', 'Commandé'), ('livré', 'Livré'), ('arrivé', 'Arrivé')], default='commandé', max_length=20),
        ),
    ]
