# Generated by Django 3.2.6 on 2021-08-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_produit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ('ordre',)},
        ),
        migrations.AddField(
            model_name='categorie',
            name='ordre',
            field=models.IntegerField(default=0),
        ),
    ]
