# Generated by Django 3.2.6 on 2021-08-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210822_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='vedette',
            field=models.BooleanField(default=False),
        ),
    ]
