# Generated by Django 3.2.6 on 2021-08-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210826_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='num_disponible',
            field=models.IntegerField(default=1),
        ),
    ]
