# Generated by Django 3.2.6 on 2021-08-27 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='NPA',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='place',
            new_name='localite',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='zipcode',
            new_name='telephone',
        ),
    ]
