# Generated by Django 3.2.6 on 2021-08-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20210827_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prenom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
