# Generated by Django 3.2.6 on 2021-08-27 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20210827_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='prenom',
        ),
    ]
